apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fiber
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fiber
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP